#!/bin/bash

#######################################################
# DOOR Protocol Deploy and Setup Script
#
# 이 스크립트는 스마트 컨트랙트를 배포하고
# 백엔드 환경변수를 자동으로 설정합니다.
#
# 사용법: 
#   ./scripts/deploy-and-setup.sh anvil     # Anvil (로컬)
#   ./scripts/deploy-and-setup.sh mantle    # Mantle Sepolia
#######################################################

NETWORK=${1:-anvil}
BACKEND_DIR="/Users/kimseoyoung/go/src/github.com/rrabit42/backend"
CONTRACT_DIR="/Users/kimseoyoung/go/src/github.com/rrabit42/contract"
FRONTEND_DIR="/Users/kimseoyoung/go/src/github.com/rrabit42/frontend"

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║     🚪 DOOR Protocol Deploy & Setup                  ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║  Network: $NETWORK"
echo "║  Contract Dir: $CONTRACT_DIR"
echo "║  Backend Dir: $BACKEND_DIR"
echo "╚══════════════════════════════════════════════════════╝"
echo ""

# Navigate to contract directory
cd "$CONTRACT_DIR"

if [ "$NETWORK" = "anvil" ]; then
    echo "📦 Deploying to Anvil (local)..."
    echo ""
    
    # Run deployment script and capture output
    OUTPUT=$(forge script script/DeployMantle.sol --rpc-url http://127.0.0.1:8545 --broadcast 2>&1)
    
    echo "$OUTPUT"
    
    # Parse addresses from output
    USDC_ADDRESS=$(echo "$OUTPUT" | grep "MockUSDC:" | awk '{print $2}')
    METH_ADDRESS=$(echo "$OUTPUT" | grep "MockMETH:" | awk '{print $2}')
    SENIOR_ADDRESS=$(echo "$OUTPUT" | grep "SeniorVault" | awk '{print $2}')
    JUNIOR_ADDRESS=$(echo "$OUTPUT" | grep "JuniorVault" | awk '{print $2}')
    CORE_ADDRESS=$(echo "$OUTPUT" | grep "CoreVault:" | awk '{print $2}')
    EPOCH_ADDRESS=$(echo "$OUTPUT" | grep "EpochManager:" | awk '{print $2}')
    SAFETY_ADDRESS=$(echo "$OUTPUT" | grep "SafetyModule:" | awk '{print $2}')
    
    RPC_URL="http://127.0.0.1:8545"
    # Anvil default private key
    PRIVATE_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
    
elif [ "$NETWORK" = "mantle" ]; then
    echo "📦 Deploying to Mantle Sepolia Testnet..."
    echo ""
    
    # Check for private key
    if [ -z "$PRIVATE_KEY" ]; then
        echo "❌ Error: PRIVATE_KEY environment variable not set"
        exit 1
    fi
    
    # Run deployment script and capture output
    OUTPUT=$(forge script script/DeployMantle.sol --rpc-url https://rpc.sepolia.mantle.xyz --broadcast 2>&1)
    
    echo "$OUTPUT"
    
    # Parse addresses from output
    USDC_ADDRESS=$(echo "$OUTPUT" | grep "MockUSDC:" | awk '{print $2}')
    METH_ADDRESS=$(echo "$OUTPUT" | grep "MockMETH:" | awk '{print $2}')
    SENIOR_ADDRESS=$(echo "$OUTPUT" | grep "SeniorVault" | awk '{print $2}')
    JUNIOR_ADDRESS=$(echo "$OUTPUT" | grep "JuniorVault" | awk '{print $2}')
    CORE_ADDRESS=$(echo "$OUTPUT" | grep "CoreVault:" | awk '{print $2}')
    EPOCH_ADDRESS=$(echo "$OUTPUT" | grep "EpochManager:" | awk '{print $2}')
    SAFETY_ADDRESS=$(echo "$OUTPUT" | grep "SafetyModule:" | awk '{print $2}')
    
    RPC_URL="https://rpc.sepolia.mantle.xyz"
else
    echo "❌ Unknown network: $NETWORK"
    echo "Usage: $0 [anvil|mantle]"
    exit 1
fi

echo ""
echo "═══════════════════════════════════════════════════"
echo "📝 Parsed Contract Addresses:"
echo "═══════════════════════════════════════════════════"
echo "USDC:          $USDC_ADDRESS"
echo "METH:          $METH_ADDRESS"
echo "SeniorVault:   $SENIOR_ADDRESS"
echo "JuniorVault:   $JUNIOR_ADDRESS"
echo "CoreVault:     $CORE_ADDRESS"
echo "EpochManager:  $EPOCH_ADDRESS"
echo "SafetyModule:  $SAFETY_ADDRESS"
echo "═══════════════════════════════════════════════════"
echo ""

# Create backend .env file
echo "📝 Creating backend .env file..."
cat > "$BACKEND_DIR/.env" << EOF
# DOOR Protocol Backend Configuration
# Auto-generated by deploy-and-setup.sh

# Server
PORT=3001

# Blockchain Configuration
RPC_URL=$RPC_URL
PRIVATE_KEY=$PRIVATE_KEY

# Contract Addresses
USDC_ADDRESS=$USDC_ADDRESS
METH_ADDRESS=$METH_ADDRESS
SENIOR_VAULT_ADDRESS=$SENIOR_ADDRESS
JUNIOR_VAULT_ADDRESS=$JUNIOR_ADDRESS
CORE_VAULT_ADDRESS=$CORE_ADDRESS
EPOCH_MANAGER_ADDRESS=$EPOCH_ADDRESS
SAFETY_MODULE_ADDRESS=$SAFETY_ADDRESS
EOF

echo "✅ Backend .env created at $BACKEND_DIR/.env"

# Update frontend addresses
echo "📝 Updating frontend contract addresses..."
cat > "$FRONTEND_DIR/src/lib/contracts/addresses.ts" << EOF
/**
 * DOOR Protocol - Contract Addresses
 * Auto-generated by deploy-and-setup.sh
 */

// Network: $NETWORK

// Core Contract Addresses
export const CORE_VAULT_ADDRESS = '$CORE_ADDRESS' as const;
export const SENIOR_TRANCHE_ADDRESS = '$SENIOR_ADDRESS' as const;
export const JUNIOR_TRANCHE_ADDRESS = '$JUNIOR_ADDRESS' as const;
export const EPOCH_MANAGER_ADDRESS = '$EPOCH_ADDRESS' as const;
export const SAFETY_MODULE_ADDRESS = '$SAFETY_ADDRESS' as const;

// Token Addresses
export const USDC_ADDRESS = '$USDC_ADDRESS' as const;
export const METH_ADDRESS = '$METH_ADDRESS' as const;

// Legacy aliases (for backward compatibility)
export const RATE_ORACLE_ADDRESS = '0x0000000000000000000000000000000000000000' as const;
export const DOOR_FIX_TOKEN_ADDRESS = '$SENIOR_ADDRESS' as const;
export const DOOR_BOOST_TOKEN_ADDRESS = '$JUNIOR_ADDRESS' as const;
export const VAULT_STRATEGY_ADDRESS = '0x0000000000000000000000000000000000000000' as const;
export const USDT_ADDRESS = '$USDC_ADDRESS' as const;
export const RWA_ADDRESS = '0x0000000000000000000000000000000000000000' as const;

// ABIs - Import from generated artifacts
export { CORE_VAULT_ABI } from './abis/CoreVault';
export { SENIOR_VAULT_ABI, JUNIOR_VAULT_ABI } from './abis/Vaults';
export { EPOCH_MANAGER_ABI } from './abis/EpochManager';
export { ERC20_ABI } from './abis/ERC20';

// Network Configuration
export const NETWORK_CONFIG = {
  name: '$NETWORK',
  rpcUrl: '$RPC_URL',
  chainId: $NETWORK === 'anvil' ? 31337 : 5003
};
EOF

echo "✅ Frontend addresses updated at $FRONTEND_DIR/src/lib/contracts/addresses.ts"

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║  ✅ Deployment and Setup Complete!                   ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║                                                      ║"
echo "║  Next Steps:                                         ║"
echo "║  1. cd $BACKEND_DIR                                  ║"
echo "║  2. npm install                                      ║"
echo "║  3. npm run dev                                      ║"
echo "║                                                      ║"
echo "║  For Frontend:                                       ║"
echo "║  1. cd $FRONTEND_DIR                                 ║"
echo "║  2. Copy ABI files (see README)                      ║"
echo "║  3. npm run dev                                      ║"
echo "║                                                      ║"
echo "╚══════════════════════════════════════════════════════╝"

